using SpiderFramework;
using SpiderFramework.Queue;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;

namespace SpiderTasks
{
    /// <summary>
    /// 
    /// </summary>
    public abstract class AutoGeneratedListTask : Task, IDatabase
    {
        public virtual int StartPageNo { get; set; }
        public virtual int EndPageNo { get; set; }
        public abstract string UrlTemplate { get; }

        public override void DoStuff()
        {
            using (MongoQueue<TaskMessage> queue = new MongoQueue<TaskMessage>(ConfigurationManager.AppSettings["mongodbqueue"], 1000000))
            {
                for (int i = StartPageNo; i <= EndPageNo; i++)
                {
                    var msg = CreatePageTask(this.Name, string.Format(UrlTemplate,i));
                    queue.Send(msg);
                }
            }
        }

        public abstract TaskMessage CreatePageTask(string name, string url);

        #region IDatabase Members

        public string ConnectionString 
        { 
            get; 
            set; 
        }

        public DatabaseType DBType
        {
            get;
            set;
        }

        #endregion
    }
}
